### ISSUE TITLE
Adding node to url

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-portal-common#130]
**Describe the bug**
adding node after click on "Login" link

**To Reproduce**
1. Go to 'https://eoscportal.docker-fid.grid.cyf-kr.edu.pl'
3. Click on Login 
5. Url is https://eoscportal.docker-fid.grid.cyf-kr.edu.pl/node
![image](https://user-images.githubusercontent.com/59872096/130792225-64ce7322-0665-444f-a75e-adc0c1bf2bbe.png)

Now this functionality does not work, to check if it looks correct for the logged in user
Ticket probably to be closed

**Comment by danielkryska** [comment]
This is a standard workflow of the Drupal SSO plugin.
